import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { poppins } from "@/utils/font";

export const metadata: Metadata = {
  title: "Sai Dental Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "font-poppins min-h-screen bg-background antialiased",
          poppins,
        )}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
